# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2022-08-26T22:25:38+00:00

from __future__ import annotations

from typing import Any, List, Optional

from pydantic import BaseModel


class ChildrenListItem(BaseModel):
    actors: Optional[List]
    added_at: Optional[str]
    art: Optional[str]
    audience_rating: Optional[str]
    audience_rating_image: Optional[str]
    banner: Optional[str]
    content_rating: Optional[str]
    directors: Optional[List]
    duration: Optional[str]
    full_title: Optional[str]
    collections: Optional[List]
    genres: Optional[List]
    grandparent_rating_key: Optional[str]
    grandparent_thumb: Optional[str]
    grandparent_title: Optional[str]
    guid: Optional[str]
    labels: Optional[List]
    last_viewed_at: Optional[str]
    library_name: Optional[str]
    media_index: Optional[str]
    media_type: Optional[str]
    original_title: Optional[str]
    originally_available_at: Optional[str]
    parent_media_index: Optional[str]
    parent_rating_key: Optional[str]
    parent_thumb: Optional[str]
    parent_title: Optional[str]
    rating: Optional[str]
    rating_image: Optional[str]
    rating_key: Optional[str]
    section_id: Optional[str]
    sort_title: Optional[str]
    studio: Optional[str]
    summary: Optional[str]
    tagline: Optional[str]
    thumb: Optional[str]
    title: Optional[str]
    updated_at: Optional[str]
    user_rating: Optional[str]
    writers: Optional[List]
    year: Optional[str]
    collections: Optional[List]


class ChildrenMetadata(BaseModel):
    children_count: Optional[int]
    children_type: Optional[str]
    title: Optional[str]
    children_list: Optional[List[ChildrenListItem]]


class Response(BaseModel):
    result: Optional[str]
    message: Any
    data: ChildrenMetadata


class Model(BaseModel):
    response: Response
