# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T04:27:48+00:00

from __future__ import annotations

from typing import Any, List, Optional

from tautulli.models._base import _Base, EmptyStringNullableInt


class DatumModel(_Base):
    addedAt: Optional[str] = None
    art: Optional[Any] = None
    childCount: EmptyStringNullableInt = None
    collectionMode: EmptyStringNullableInt = None
    collectionSort: EmptyStringNullableInt = None
    contentRating: Optional[str] = None
    guid: Optional[str] = None
    librarySectionID: Optional[str] = None
    librarySectionTitle: Optional[str] = None
    maxYear: EmptyStringNullableInt = None
    minYear: EmptyStringNullableInt = None
    ratingKey: EmptyStringNullableInt = None
    subtype: Optional[str] = None
    summary: Optional[str] = None
    thumb: Optional[str] = None
    title: Optional[str] = None
    titleSort: Optional[str] = None
    type: Optional[str] = None
    updatedAt: Optional[str] = None


class CollectionsTableModel(_Base):
    recordsFiltered: EmptyStringNullableInt = None
    recordsTotal: EmptyStringNullableInt = None
    data: Optional[List[DatumModel]] = None
    draw: EmptyStringNullableInt = None



