# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T03:50:33+00:00

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel


class DateFormats(BaseModel):
    date_format: Optional[str]
    time_format: Optional[str]


class Response(BaseModel):
    result: Optional[str]
    message: Any
    data: DateFormats


class Model(BaseModel):
    response: Response
