# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T03:50:33+00:00

from __future__ import annotations

from typing import Optional

from tautulli.models._base import _Base


class DateFormatsModel(_Base):
    date_format: Optional[str] = None
    time_format: Optional[str] = None
