# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2022-08-26T22:20:41+00:00

from __future__ import annotations

from typing import Any, List, Optional

from pydantic import BaseModel


class MetadataField(BaseModel):
    field: Optional[str] = None
    level: Optional[int] = None


class MediaInfoField(BaseModel):
    field: Optional[str] = None
    level: Optional[int] = None


class ExportFields(BaseModel):
    metadata_fields: Optional[List[MetadataField]] = None
    media_info_fields: Optional[List[MediaInfoField]] = None


class Response(BaseModel):
    result: str
    message: Any = None
    data: ExportFields


class Model(BaseModel):
    response: Response
