# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2022-08-26T22:23:14+00:00

from __future__ import annotations

from typing import Any, List, Optional

from pydantic import BaseModel


class Datum(BaseModel):
    timestamp: int
    art_level: int
    complete: int
    custom_fields: str
    exists: bool
    export_id: int
    exported_items: int
    file_format: str
    file_size: int
    filename: Any
    individual_files: int
    media_info_level: int
    media_type: str
    media_type_title: str
    metadata_level: int
    rating_key: Any
    section_id: int
    thumb_level: int
    title: str
    total_items: int
    user_id: Any


class Data(BaseModel):
    draw: int
    recordsTotal: int
    recordsFiltered: int
    data: List[Datum]


class Response(BaseModel):
    result: str
    message: Any
    data: Data


class Model(BaseModel):
    response: Response
