# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T04:34:08+00:00

from __future__ import annotations

from typing import Any, Optional

from tautulli.models._base import _Base, EmptyStringNullableFloat


class GeoIPLookupModel(_Base):
    city: Optional[str] = None
    code: Optional[str] = None
    continent: Optional[str] = None
    country: Optional[str] = None
    latitude: EmptyStringNullableFloat = None
    longitude: EmptyStringNullableFloat = None
    postal_code: Optional[str] = None
    region: Optional[str] = None
    timezone: Optional[str] = None
    accuracy: Optional[Any] = None



