# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2022-08-26T20:59:57+00:00

from __future__ import annotations

from typing import List, Optional

from tautulli.models._base import _Base


class SeriesModel(_Base):
    name: Optional[str] = None
    data: Optional[List] = None


class PlaysOrStreamTypesByModel(_Base):
    categories: Optional[List[str]] = None
    series: Optional[List[SeriesModel]] = None



