# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T04:35:02+00:00

from __future__ import annotations

from typing import Any, List, Union, Optional

from pydantic import BaseModel


class Datum(BaseModel):
    reference_id: int
    row_id: int
    id: int
    date: int
    started: int
    stopped: int
    duration: int
    paused_counter: int
    user_id: int
    user: Optional[str]
    friendly_name: Optional[str]
    platform: Optional[str]
    product: Optional[str]
    player: Optional[str]
    ip_address: Optional[str]
    live: int
    machine_id: Optional[str]
    media_type: Optional[str]
    rating_key: int
    parent_rating_key: Union[int, str]
    grandparent_rating_key: Union[int, str]
    full_title: Optional[str]
    title: Optional[str]
    parent_title: Optional[str]
    grandparent_title: Optional[str]
    original_title: Optional[str]
    year: Union[int, str]
    media_index: Union[int, str]
    parent_media_index: Union[int, str]
    thumb: Optional[str]
    originally_available_at: Optional[str]
    guid: Optional[str]
    transcode_decision: Optional[str]
    percent_complete: int
    watched_status: float
    group_count: int
    group_ids: Optional[str]
    state: Any
    session_key: Any


class Data(BaseModel):
    recordsFiltered: int
    recordsTotal: int
    data: List[Datum]
    draw: int
    filter_duration: Optional[str]
    total_duration: Optional[str]


class Response(BaseModel):
    result: Optional[str]
    message: Any
    data: Data


class Model(BaseModel):
    response: Response
