# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2022-08-26T19:32:43+00:00

from __future__ import annotations

from typing import List, Optional, Any

from pydantic import BaseModel


class ItemUserStat(BaseModel):
    friendly_name: Optional[str]
    user_id: Optional[int]
    user_thumb: Optional[str]
    username: Optional[str]
    total_plays: Optional[int]
    total_time: Optional[int]


class Response(BaseModel):
    result: Optional[str]
    message: Any
    data: List[ItemUserStat]


class Model(BaseModel):
    response: Response
