# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2022-08-26T19:37:39+00:00

from __future__ import annotations

from tautulli.models._base import _Base, EmptyStringNullableInt


class ItemWatchTimeStatModel(_Base):
    query_days: EmptyStringNullableInt = None
    total_time: EmptyStringNullableInt = None
    total_plays: EmptyStringNullableInt = None



