# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2022-08-26T19:37:39+00:00

from __future__ import annotations

from typing import List, Optional, Any

from pydantic import BaseModel


class ItemWatchTimeStat(BaseModel):
    query_days: Optional[int]
    total_time: Optional[int]
    total_plays: Optional[int]


class Response(BaseModel):
    result: Optional[str]
    message: Any
    data: List[ItemWatchTimeStat]


class Model(BaseModel):
    response: Response
