# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T04:36:07+00:00

from __future__ import annotations

from typing import Optional

from tautulli.models._base import _Base, EmptyStringNullableInt


class LibrariesEntryModel(_Base):
    section_id: Optional[str] = None
    section_name: Optional[str] = None
    section_type: Optional[str] = None
    agent: Optional[str] = None
    thumb: Optional[str] = None
    art: Optional[str] = None
    count: Optional[str] = None
    is_active: EmptyStringNullableInt = None
    parent_count: Optional[str] = None
    child_count: Optional[str] = None



