# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T04:38:24+00:00

from __future__ import annotations

from typing import Any, List, Optional

from pydantic import BaseModel


class Datum(BaseModel):
    video_resolution: Optional[str]
    audio_channels: Optional[str]
    container: Optional[str]
    thumb: Optional[str]
    media_index: Optional[str]
    title: Optional[str]
    bitrate: Optional[str]
    video_codec: Optional[str]
    section_type: Optional[str]
    section_id: Optional[int]
    added_at: Optional[str]
    sort_title: Optional[str]
    file_size: Optional[str]
    parent_rating_key: Optional[str]
    audio_codec: Optional[str]
    year: Optional[str]
    media_type: Optional[str]
    parent_media_index: Optional[str]
    grandparent_rating_key: Optional[str]
    rating_key: Optional[str]
    video_framerate: Optional[str]
    last_played: Optional[int]
    play_count: Optional[int]


class LibraryMediaInfo(BaseModel):
    recordsFiltered: Optional[int]
    recordsTotal: Optional[int]
    data: Optional[List[Datum]]
    draw: Optional[int]
    last_refreshed: Optional[int]
    filtered_file_size: Optional[int]
    total_file_size: Optional[int]


class Response(BaseModel):
    result: Optional[str]
    message: Any
    data: LibraryMediaInfo


class Model(BaseModel):
    response: Response
