# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T04:39:18+00:00

from __future__ import annotations

from typing import Any, List, Optional

from pydantic import BaseModel


class LibraryWatchTimeStats(BaseModel):
    query_days: Optional[int] = None
    total_time: Optional[int] = None
    total_plays: Optional[int] = None


class Response(BaseModel):
    result: Optional[str] = None
    message: Any = None
    data: List[LibraryWatchTimeStats]


class Model(BaseModel):
    response: Response
