# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T04:37:27+00:00

from __future__ import annotations

from typing import List, Optional

from tautulli.models._base import _Base, EmptyStringNullableInt


class DatumModel(_Base):
    row_id: EmptyStringNullableInt = None
    server_id: Optional[str] = None
    section_id: EmptyStringNullableInt = None
    section_name: Optional[str] = None
    section_type: Optional[str] = None
    count: EmptyStringNullableInt = None
    parent_count: EmptyStringNullableInt = None
    child_count: EmptyStringNullableInt = None
    library_thumb: Optional[str] = None
    library_art: Optional[str] = None
    plays: EmptyStringNullableInt = None
    duration: EmptyStringNullableInt = None
    last_accessed: EmptyStringNullableInt = None
    history_row_id: EmptyStringNullableInt = None
    last_played: Optional[str] = None
    rating_key: EmptyStringNullableInt = None
    media_type: Optional[str] = None
    thumb: Optional[str] = None
    parent_title: Optional[str] = None
    year: EmptyStringNullableInt = None
    media_index: EmptyStringNullableInt = None
    parent_media_index: EmptyStringNullableInt = None
    content_rating: Optional[str] = None
    labels: Optional[List] = None
    live: EmptyStringNullableInt = None
    originally_available_at: Optional[str] = None
    guid: Optional[str] = None
    do_notify: EmptyStringNullableInt = None
    do_notify_created: EmptyStringNullableInt = None
    keep_history: EmptyStringNullableInt = None
    is_active: EmptyStringNullableInt = None


class LibrariesTableModel(_Base):
    recordsFiltered: EmptyStringNullableInt = None
    recordsTotal: EmptyStringNullableInt = None
    data: Optional[List[DatumModel]] = None
    draw: EmptyStringNullableInt = None



