# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T04:38:24+00:00

from __future__ import annotations

from typing import List, Optional

from tautulli.models._base import _Base, EmptyStringNullableInt


class DatumModel(_Base):
    video_resolution: Optional[str] = None
    audio_channels: Optional[str] = None
    container: Optional[str] = None
    thumb: Optional[str] = None
    media_index: Optional[str] = None
    title: Optional[str] = None
    bitrate: Optional[str] = None
    video_codec: Optional[str] = None
    section_type: Optional[str] = None
    section_id: EmptyStringNullableInt = None
    added_at: Optional[str] = None
    sort_title: Optional[str] = None
    file_size: Optional[str] = None
    parent_rating_key: Optional[str] = None
    audio_codec: Optional[str] = None
    year: Optional[str] = None
    media_type: Optional[str] = None
    parent_media_index: Optional[str] = None
    grandparent_rating_key: Optional[str] = None
    rating_key: Optional[str] = None
    video_framerate: Optional[str] = None
    last_played: EmptyStringNullableInt = None
    play_count: EmptyStringNullableInt = None


class LibraryMediaInfoModel(_Base):
    recordsFiltered: EmptyStringNullableInt = None
    recordsTotal: EmptyStringNullableInt = None
    data: Optional[List[DatumModel]] = None
    draw: EmptyStringNullableInt = None
    last_refreshed: EmptyStringNullableInt = None
    filtered_file_size: EmptyStringNullableInt = None
    total_file_size: EmptyStringNullableInt = None



