# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T03:51:24+00:00

from __future__ import annotations

from typing import Any, List, Optional

from pydantic import BaseModel


class LibraryName(BaseModel):
    section_id: Optional[int]
    section_name: Optional[str]
    section_type: Optional[str]
    agent: Optional[str]


class Response(BaseModel):
    result: Optional[str]
    message: Any
    data: List[LibraryName]


class Model(BaseModel):
    response: Response
