# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T04:36:07+00:00

from __future__ import annotations

from typing import Any, List, Optional

from pydantic import BaseModel


class LibrariesEntry(BaseModel):
    section_id: Optional[str]
    section_name: Optional[str]
    section_type: Optional[str]
    agent: Optional[str]
    thumb: Optional[str]
    art: Optional[str]
    count: Optional[str]
    is_active: Optional[int]
    parent_count: Optional[str] = None
    child_count: Optional[str] = None


class Response(BaseModel):
    result: Optional[str]
    message: Any
    data: List[LibrariesEntry]


class Model(BaseModel):
    response: Response
