# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T04:37:01+00:00

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel


class Library(BaseModel):
    row_id: Optional[int]
    server_id: Optional[str]
    section_id: Optional[int]
    section_name: Optional[str]
    section_type: Optional[str]
    library_thumb: Optional[str]
    library_art: Optional[str]
    count: Optional[int]
    parent_count: Optional[Any]
    child_count: Optional[Any]
    is_active: Optional[int]
    do_notify: Optional[int]
    do_notify_created: Optional[int]
    keep_history: Optional[int]
    deleted_section: Optional[int]


class Response(BaseModel):
    result: Optional[str]
    message: Any
    data: Library


class Model(BaseModel):
    response: Response
