# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T04:43:17+00:00

from __future__ import annotations

from typing import Optional

from tautulli.models._base import _Base, Field, EmptyStringNullableInt


class Field0Model(_Base):
    rating_key: EmptyStringNullableInt = None


class NewRatingKeysModel(_Base):
    field_0: Optional[Field0Model] = Field(..., alias='0')



