# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T04:44:54+00:00

from __future__ import annotations

from typing import List, Optional, Union

from pydantic import BaseModel, Field


class Config(BaseModel):
    custom_cron: int
    time_frame: int
    time_frame_units: Optional[str]
    formatted: int
    threaded: int
    notifier_id: int
    filename: Optional[str]
    save_only: int
    incl_libraries: List[str]


class EmailConfig(BaseModel):
    from_name: Optional[str]
    from_: Optional[str] = Field(..., alias='from')
    to: List[str]
    cc: List
    bcc: List
    smtp_server: Optional[str]
    smtp_port: int
    smtp_user: Optional[str]
    smtp_password: Optional[str]
    tls: int
    html_support: int
    notifier_id: int


class MovieLibrary(BaseModel):
    value: int
    text: Optional[str]


class TVShowLibrary(BaseModel):
    value: int
    text: Optional[str]


class MusicLibrary(BaseModel):
    value: int
    text: Optional[str]


class OtherVideoLibrary(BaseModel):
    value: int
    text: Optional[str]


class SelectOptions(BaseModel):
    Movie_Libraries: List[MovieLibrary] = Field(..., alias='Movie Libraries')
    TV_Show_Libraries: List[TVShowLibrary] = Field(..., alias='TV Show Libraries')
    Music_Libraries: List[MusicLibrary] = Field(..., alias='Music Libraries')
    Other_Video_Libraries: List[OtherVideoLibrary] = Field(
        ..., alias='Other Video Libraries'
    )


class ConfigOption(BaseModel):
    label: Optional[str]
    value: List[str]
    description: Optional[str]
    name: Optional[str]
    input_type: Optional[str]
    select_options: SelectOptions


class SelectOption(BaseModel):
    value: Optional[str]
    text: Optional[str]


class EmailConfigOption(BaseModel):
    label: Optional[str]
    value: Union[Union[int, str], List[str]]
    name: Optional[str]
    description: Optional[str]
    input_type: Optional[str]
    select_options: Optional[List[SelectOption]] = None


class Data(BaseModel):
    id: int
    agent_id: int
    agent_name: Optional[str]
    agent_label: Optional[str]
    friendly_name: Optional[str]
    cron: Optional[str]
    active: int
    id_name: Optional[str]
    subject: Optional[str]
    body: Optional[str]
    config: Config
    email_config: EmailConfig
    config_options: List[ConfigOption]
    email_config_options: List[EmailConfigOption]


class Response(BaseModel):
    result: Optional[str]
    message: Optional[str]
    data: Data


class Model(BaseModel):
    response: Response
