# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T04:45:21+00:00

from __future__ import annotations

from typing import List, Optional

from tautulli.models._base import _Base, EmptyStringNullableInt


class DatumModel(_Base):
    id: EmptyStringNullableInt = None
    timestamp: EmptyStringNullableInt = None
    newsletter_id: EmptyStringNullableInt = None
    agent_id: EmptyStringNullableInt = None
    agent_name: Optional[str] = None
    notify_action: Optional[str] = None
    subject_text: Optional[str] = None
    body_text: Optional[str] = None
    start_date: Optional[str] = None
    end_date: Optional[str] = None
    uuid: Optional[str] = None
    success: EmptyStringNullableInt = None


class NewsletterLogModel(_Base):
    recordsFiltered: EmptyStringNullableInt = None
    recordsTotal: EmptyStringNullableInt = None
    data: Optional[List[DatumModel]] = None
    draw: EmptyStringNullableInt = None



