# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T03:52:33+00:00

from __future__ import annotations

from tautulli.models._base import _Base, EmptyStringNullableInt


class NewsletterNotificationModel(_Base):
    newsletter_notification_id: EmptyStringNullableInt = None



