# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T04:45:45+00:00

from __future__ import annotations

from typing import Any, List, Optional

from pydantic import BaseModel


class Datum(BaseModel):
    id: int
    timestamp: int
    session_key: int
    rating_key: int
    user_id: int
    user: Optional[str]
    notifier_id: int
    agent_id: int
    agent_name: Optional[str]
    notify_action: Optional[str]
    subject_text: Optional[str]
    body_text: Optional[str]
    success: int


class Data(BaseModel):
    recordsFiltered: int
    recordsTotal: int
    data: List[Datum]
    draw: int


class Response(BaseModel):
    result: Optional[str]
    message: Any
    data: Data


class Model(BaseModel):
    response: Response
