# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T04:48:59+00:00

from __future__ import annotations

from typing import Optional

from tautulli.models._base import _Base, EmptyStringNullableInt


class NotifierModel(_Base):
    id: EmptyStringNullableInt = None
    agent_id: EmptyStringNullableInt = None
    agent_name: Optional[str] = None
    agent_label: Optional[str] = None
    friendly_name: Optional[str] = None
    active: EmptyStringNullableInt = None



