# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2022-08-26T22:43:25+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional, Union

from tautulli.models._base import _Base, EmptyStringNullableInt


class ConfigModel(_Base):
    incl_poster: EmptyStringNullableInt = None
    html_support: EmptyStringNullableInt = None
    chat_id: Optional[str] = None
    bot_token: Optional[str] = None
    incl_subject: EmptyStringNullableInt = None
    disable_web_preview: EmptyStringNullableInt = None


class ActionsModel(_Base):
    on_play: EmptyStringNullableInt = None
    on_stop: EmptyStringNullableInt = None


class OnPlayModel(_Base):
    subject: Optional[str] = None
    body: Optional[str] = None


class OnStopModel(_Base):
    subject: Optional[str] = None
    body: Optional[str] = None


class NotifyTextModel(_Base):
    on_play: Optional[OnPlayModel] = None
    on_stop: Optional[OnStopModel] = None


class NotifierConfigModel(_Base):
    id: EmptyStringNullableInt = None
    agent_id: EmptyStringNullableInt = None
    agent_name: Optional[str] = None
    agent_label: Optional[str] = None
    friendly_name: Optional[str] = None
    config: Optional[ConfigModel] = None
    config_options: Optional[List[Union[Dict[str, Any], str]]] = None
    actions: Optional[ActionsModel] = None
    notify_text: Optional[NotifyTextModel] = None



