# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T04:45:45+00:00

from __future__ import annotations

from typing import List, Optional

from tautulli.models._base import _Base, EmptyStringNullableInt


class DatumModel(_Base):
    id: EmptyStringNullableInt = None
    timestamp: EmptyStringNullableInt = None
    session_key: EmptyStringNullableInt = None
    rating_key: EmptyStringNullableInt = None
    user_id: EmptyStringNullableInt = None
    user: Optional[str] = None
    notifier_id: EmptyStringNullableInt = None
    agent_id: EmptyStringNullableInt = None
    agent_name: Optional[str] = None
    notify_action: Optional[str] = None
    subject_text: Optional[str] = None
    body_text: Optional[str] = None
    success: EmptyStringNullableInt = None


class NotificationLogModel(_Base):
    recordsFiltered: EmptyStringNullableInt = None
    recordsTotal: EmptyStringNullableInt = None
    data: Optional[List[DatumModel]] = None
    draw: EmptyStringNullableInt = None



