# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T04:51:11+00:00

from __future__ import annotations

from typing import Any, List, Optional

from pydantic import BaseModel


class Datum(BaseModel):
    addedAt: Optional[str] = None
    composite: Optional[str] = None
    duration: Optional[int] = None
    guid: Optional[str] = None
    leafCount: Optional[int] = None
    librarySectionID: Optional[str] = None
    playlistType: Optional[str] = None
    ratingKey: Optional[int] = None
    smart: Optional[bool] = None
    summary: Optional[str] = None
    title: Optional[str] = None
    type: Optional[str] = None
    updatedAt: Optional[str] = None
    userID: Optional[Any] = None


class PlaylistsTable(BaseModel):
    recordsFiltered: Optional[int] = None
    recordsTotal: Optional[int] = None
    data: Optional[List[Datum]] = None
    draw: Optional[int] = None


class Response(BaseModel):
    result: Optional[str] = None
    message: Any = None
    data: PlaylistsTable


class Model(BaseModel):
    response: Response
