# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T03:57:17+00:00

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel


class PMSUpdate(BaseModel):
    update_available: Optional[bool]
    platform: Optional[str]
    release_date: Optional[int]
    version: Optional[str]
    requirements: Optional[str]
    extra_info: Optional[str]
    changelog_added: Optional[str]
    changelog_fixed: Optional[str]
    label: Optional[str]
    distro: Optional[str]
    distro_build: Optional[str]
    download_url: Optional[str]


class Response(BaseModel):
    result: Optional[str]
    message: Any
    data: PMSUpdate


class Model(BaseModel):
    response: Response
