# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T05:07:40+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class RegisteredDevice(BaseModel):
    server_id: Optional[str]
    pms_name: Optional[str]
    pms_version: Optional[str]
    pms_platform: Optional[str]
    pms_ip: Optional[str]
    pms_port: Optional[int]
    pms_ssl: Optional[int]
    pms_is_remote: Optional[int]
    pms_is_cloud: Optional[int]
    pms_url: Optional[str]
    pms_url_manual: Optional[int]
    pms_identifier: Optional[str]
    pms_plexpass: Optional[int]
    tautulli_install_type: Optional[str]
    tautulli_version: Optional[str]
    tautulli_branch: Optional[str]
    tautulli_commit: Optional[str]
    tautulli_platform: Optional[str]
    tautulli_platform_release: Optional[str]
    tautulli_platform_version: Optional[str]
    tautulli_platform_linux_distro: Optional[str]
    tautulli_platform_device_name: Optional[str]
    tautulli_python_version: Optional[str]


class Response(BaseModel):
    result: Optional[str]
    message: Optional[str]
    data: RegisteredDevice


class Model(BaseModel):
    response: Response
