# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T04:21:25+00:00

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel


class ServerInfo(BaseModel):
    pms_name: Optional[str]
    pms_version: Optional[str]
    pms_platform: Optional[str]
    pms_ip: Optional[str]
    pms_port: Optional[int]
    pms_ssl: Optional[int]
    pms_is_remote: Optional[int]
    pms_url: Optional[str]
    pms_url_manual: Optional[int]
    pms_identifier: Optional[str]
    pms_plexpass: Optional[int]


class Response(BaseModel):
    result: Optional[str]
    message: Any
    data: ServerInfo


class Model(BaseModel):
    response: Response
