# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T04:21:25+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class Data(BaseModel):
    pms_name: str
    pms_version: str
    pms_platform: str
    pms_ip: str
    pms_port: int
    pms_ssl: int
    pms_is_remote: int
    pms_url: str
    pms_url_manual: int
    pms_identifier: str
    pms_plexpass: int


class Response(BaseModel):
    result: str
    message: Any
    data: Data


class Model(BaseModel):
    response: Response
