# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T04:21:25+00:00

from __future__ import annotations

from typing import Optional

from tautulli.models._base import _Base, EmptyStringNullableInt


class ServerInfoModel(_Base):
    pms_name: Optional[str] = None
    pms_version: Optional[str] = None
    pms_platform: Optional[str] = None
    pms_ip: Optional[str] = None
    pms_port: EmptyStringNullableInt = None
    pms_ssl: EmptyStringNullableInt = None
    pms_is_remote: EmptyStringNullableInt = None
    pms_url: Optional[str] = None
    pms_url_manual: EmptyStringNullableInt = None
    pms_identifier: Optional[str] = None
    pms_plexpass: EmptyStringNullableInt = None



