# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T04:52:30+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class Data(BaseModel):
    identifier: Any


class Response(BaseModel):
    result: str
    message: Any
    data: Data


class Model(BaseModel):
    response: Response
