# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T03:58:36+00:00

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel


class ServerIdentity(BaseModel):
    machine_identifier: Optional[str]
    version: Optional[str]


class Response(BaseModel):
    result: Optional[str]
    message: Any
    data: ServerIdentity


class Model(BaseModel):
    response: Response
