# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2022-08-26T22:18:10+00:00

from __future__ import annotations

from typing import Optional

from tautulli.models._base import _Base


class ServerStatusModel(_Base):
    result: Optional[str] = None
    connected: Optional[bool] = None



