# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2022-08-26T22:18:10+00:00

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel


class ServerStatus(BaseModel):
    result: Optional[str]
    connected: Optional[bool]


class Response(BaseModel):
    result: str
    message: Any
    data: ServerStatus


class Model(BaseModel):
    response: Response
