# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T04:22:54+00:00

from __future__ import annotations

from typing import Any, List, Optional

from pydantic import BaseModel


class ServersInfoEntry(BaseModel):
    name: Optional[str]
    machine_identifier: Optional[str]
    host: Optional[str]
    port: Optional[str]
    version: Optional[str]


class Response(BaseModel):
    result: Optional[str]
    message: Any
    data: List[ServersInfoEntry]


class Model(BaseModel):
    response: Response
