# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T03:58:36+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class Data(BaseModel):
    machine_identifier: str
    version: str


class Response(BaseModel):
    result: str
    message: Any
    data: Data


class Model(BaseModel):
    response: Response
