# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T04:22:02+00:00

from __future__ import annotations

from typing import Any, List, Optional

from pydantic import BaseModel


class ServerListEntry(BaseModel):
    httpsRequired: Optional[str]
    clientIdentifier: Optional[str]
    label: Optional[str]
    ip: Optional[str]
    port: Optional[str]
    uri: Optional[str]
    local: Optional[str]
    value: Optional[str]
    is_cloud: Optional[bool]


class Response(BaseModel):
    result: Optional[str]
    message: Any
    data: List[ServerListEntry]


class Model(BaseModel):
    response: Response
