# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T04:34:08+00:00

from __future__ import annotations

from typing import Any, Optional

from tautulli.models._base import _Base


class StatusModel(_Base):
    result: Optional[str] = None
    message: Any = None
