# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2022-02-20T07:32:48+00:00

from __future__ import annotations

from pydantic import BaseModel


class Data(BaseModel):
    tautulli_install_type: str
    tautulli_version: str
    tautulli_branch: str
    tautulli_commit: str
    tautulli_platform: str
    tautulli_platform_release: str
    tautulli_platform_version: str
    tautulli_platform_linux_distro: str
    tautulli_platform_device_name: str
    tautulli_python_version: str


class Model(BaseModel):
    result: str
    message: str
    data: Data
