# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T04:26:04+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class UpdateCheck(BaseModel):
    update: Optional[bool] = None
    install_type: Optional[str] = None


class Response(BaseModel):
    result: Optional[str] = None
    message: Optional[str] = None
    data: UpdateCheck


class Model(BaseModel):
    response: Response
