# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T05:02:13+00:00

from __future__ import annotations

from typing import Any, List, Optional

from pydantic import BaseModel


class Datum(BaseModel):
    friendly_name: Optional[str]
    guid: Optional[str]
    id: Optional[int]
    ip_address: Optional[str]
    last_played: Optional[str]
    last_seen: Optional[int]
    first_seen: Optional[int]
    live: Optional[int]
    media_index: Optional[int]
    media_type: Optional[str]
    originally_available_at: Optional[str]
    parent_media_index: Optional[int]
    parent_title: Optional[str]
    platform: Optional[str]
    play_count: Optional[int]
    player: Optional[str]
    rating_key: Optional[int]
    thumb: Optional[str]
    transcode_decision: Optional[str]
    user_id: Optional[int]
    year: Optional[int]


class UserIPs(BaseModel):
    draw: Optional[int]
    recordsTotal: Optional[int]
    recordsFiltered: Optional[int]
    data: Optional[List[Datum]]


class Response(BaseModel):
    result: Optional[str]
    message: Any
    data: UserIPs


class Model(BaseModel):
    response: Response
