# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T04:59:53+00:00

from __future__ import annotations

from typing import List, Optional

from tautulli.models._base import _Base, EmptyStringNullableInt


class UserModel(_Base):
    row_id: EmptyStringNullableInt = None
    user_id: EmptyStringNullableInt = None
    username: Optional[str] = None
    friendly_name: Optional[str] = None
    user_thumb: Optional[str] = None
    email: Optional[str] = None
    is_active: EmptyStringNullableInt = None
    is_admin: EmptyStringNullableInt = None
    is_home_user: EmptyStringNullableInt = None
    is_allow_sync: EmptyStringNullableInt = None
    is_restricted: EmptyStringNullableInt = None
    do_notify: EmptyStringNullableInt = None
    keep_history: EmptyStringNullableInt = None
    allow_guest: EmptyStringNullableInt = None
    deleted_user: EmptyStringNullableInt = None
    shared_libraries: Optional[List] = None



