# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T05:05:19+00:00

from __future__ import annotations

from tautulli.models._base import _Base, EmptyStringNullableInt


class UserWatchTimeStatsModel(_Base):
    query_days: EmptyStringNullableInt = None
    total_plays: EmptyStringNullableInt = None
    total_time: EmptyStringNullableInt = None



