# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T04:59:53+00:00

from __future__ import annotations

from typing import Any, List, Optional

from pydantic import BaseModel


class Data(BaseModel):
    row_id: int
    user_id: int
    username: Optional[str]
    friendly_name: Optional[str]
    user_thumb: Optional[str]
    email: Optional[str]
    is_active: int
    is_admin: Optional[str]
    is_home_user: int
    is_allow_sync: int
    is_restricted: int
    do_notify: int
    keep_history: int
    allow_guest: int
    deleted_user: int
    shared_libraries: List


class Response(BaseModel):
    result: Optional[str]
    message: Any
    data: Data


class Model(BaseModel):
    response: Response
