# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T04:24:09+00:00

from __future__ import annotations

from typing import Any, List, Optional

from pydantic import BaseModel


class UserNameModel(BaseModel):
    user_id: Optional[int] = None
    friendly_name: Optional[str] = None



