# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T04:24:09+00:00

from __future__ import annotations

from typing import Any, List, Optional

from pydantic import BaseModel


class UserName(BaseModel):
    user_id: Optional[int]
    friendly_name: Optional[str]


class Response(BaseModel):
    result: Optional[str]
    message: Any
    data: List[UserName]


class Model(BaseModel):
    response: Response
