# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T04:24:52+00:00

from __future__ import annotations

from typing import Any, List, Optional

from pydantic import BaseModel


class User(BaseModel):
    row_id: Optional[int]
    user_id: Optional[int]
    username: Optional[str]
    friendly_name: Optional[str]
    thumb: Optional[str]
    email: Optional[str]
    is_active: Optional[int]
    is_admin: Optional[int]
    is_home_user: Optional[int]
    is_allow_sync: Optional[int]
    is_restricted: Optional[int]
    do_notify: Optional[int]
    keep_history: Optional[int]
    allow_guest: Optional[int]
    shared_libraries: Optional[List[str]]
    filter_all: Optional[str]
    filter_movies: Optional[str]
    filter_tv: Optional[str]
    filter_music: Optional[str]
    filter_photos: Optional[str]


class Response(BaseModel):
    result: Optional[str]
    message: Any
    data: List[User]


class Model(BaseModel):
    response: Response
