# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T05:02:13+00:00

from __future__ import annotations

from typing import Any, List, Optional

from pydantic import BaseModel


class Datum(BaseModel):
    friendly_name: Optional[str]
    guid: Optional[str]
    id: int
    ip_address: Optional[str]
    last_played: Optional[str]
    last_seen: int
    first_seen: int
    live: int
    media_index: int
    media_type: Optional[str]
    originally_available_at: Optional[str]
    parent_media_index: int
    parent_title: Optional[str]
    platform: Optional[str]
    play_count: int
    player: Optional[str]
    rating_key: int
    thumb: Optional[str]
    transcode_decision: Optional[str]
    user_id: int
    year: int


class Data(BaseModel):
    draw: int
    recordsTotal: int
    recordsFiltered: int
    data: List[Datum]


class Response(BaseModel):
    result: Optional[str]
    message: Any
    data: Data


class Model(BaseModel):
    response: Response
