# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-01-27T05:04:32+00:00

from __future__ import annotations

from typing import Optional

from tautulli.models._base import _Base, EmptyStringNullableInt


class UserPlayerStatsModel(_Base):
    platform: Optional[str] = None
    platform_name: Optional[str] = None
    player_name: Optional[str] = None
    result_id: EmptyStringNullableInt = None
    total_plays: EmptyStringNullableInt = None



